global:
  scrape_interval: 15s

remote_write:
  - url: http://localhost:8428/api/v1/write # remote storage victoria-metrics listening prot

scrape_configs:
  - job_name: node_server
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8090'] # prom-htpp-server listening port
