name: analyze bundle

on:
  # pull_request:
  # branches: ['master']

  push:

jobs:
  ls:
    name: ls & file
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: debug - file
        run: cd src/public && ls -l && file './constants.ts'

  symlink:
    name: symlink & cat
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: symlink
        run: npm run symLink

      - name: cat
        run: cd src/public && ls -l && cat './constants.ts'

  build:
    name: analyse bundle - 改别名 + 使用 originalpath
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      # - name: install webpack
      #   run: npm i webpack -g

      - name: check webpack version
        run: npx webpack -v

      - name: debug
        run: npm run debug

      - name: debug - ls
        run: ls src/public

      - name: debug - cat
        run: cd src/public && cat './constants.ts'

      - name: build
        run: npm run build
